### ISSUE TITLE
Add missing mappings

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/government-procurement-agreement#12]
Articles:

* [x] VII:3
* [x] VII:4
* [x] VII:5
* [ ] IX:8 #22
* [ ] IX:9 #22
* [x] X:7
* [x] X:9
* [x] X:11
* [ ] XI:4 (need to add to spreadsheet below) #29
* [x] XIII:2
* [x] XIV:1
* [x] XVI:2

https://docs.google.com/spreadsheets/d/1tFPC0V9HV3iK6yy0QVw2J8A3jU8dQCQS83KXQSxeT1E/edit#gid=846654670

**Comment by ColinMaudry** [comment]
@jpmckinney Who did the spreadsheet https://docs.google.com/spreadsheets/d/1tFPC0V9HV3iK6yy0QVw2J8A3jU8dQCQS83KXQSxeT1E/edit#gid=846654670 ?

**Comment by jpmckinney** [comment]
Simon Whitehouse did the original mapping in 2017, and I reviewed it that year. I might not make the same choices if I were to do it again now, so feel free to suggest alternatives :)

**Comment by ColinMaudry** [comment]
Yes, I would change a couple of things, but it gives good pointers :)

**Comment by jpmckinney** [comment]
I think we have open issues for the remaining articles, so closing :)
