### ISSUE TITLE
Update mapping to match changes to options extension

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/government-procurement-agreement#15]

**Comment by ColinMaudry** [comment]
Changes in the mapping?

**Comment by ColinMaudry** [comment]
Ah, no, the contrary. OK!

**Comment by ColinMaudry** [comment]
You mean updating the GPA mapping, or the EU mapping? Or both?

**Comment by jpmckinney** [comment]
I think the EU mapping is already up-to-date, but the GPA mapping still corresponds to the original options extension, and needs to be updated to account for recent changes.

**Comment by jpmckinney** [comment]
Closed by #17
