### ISSUE TITLE
Update GPA mappings to match new OCDS for EU extensions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/government-procurement-agreement#18]
* [x] Place of performance
* [x] Options

There might be other mappings to update.

**Comment by ColinMaudry** [comment]
Options seem to be covered in VII:2(d).

**Comment by ColinMaudry** [comment]
I couldn't find a reference to Place of performance or `.deliveryAddress`in the current mapping.

**Comment by jpmckinney** [comment]
I'm not sure what I was thinking :) If the mapping now looks consistent with the EU work, then we can close this issue.

**Comment by ColinMaudry** [comment]
I didn't say that it looks consistent with the EU work, simply that Place of performance and Options look good. To be continued in #21
