### ISSUE TITLE
Adjust existing mappings

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/government-procurement-agreement#21]
* [x] Describe potential to use `documents` (e.g. in addition to `tender/description`) in cases where documents are available
* [x] Mention the availability of `options` and `recurrence` on lots, in cases where the procurement is divided into lots
* [x] Review my earlier [code mappings](https://docs.google.com/spreadsheets/d/1X4nULP8nhYR_iXra0HjTy5n2v5z2kyzFFT7KTv2GZo0/edit#gid=0)

**Comment by ColinMaudry** [comment]
I think items 1 and 3 are done.

The articles of the GPA you picked for the mapping don't seem to mention lots, options nor recurrence.

Did I miss something?

**Comment by jpmckinney** [comment]
For lots, I think if the publisher is going beyond the GPA, then they'll look for other OCDS documentation, so we don't need to describe all the possibilities here.
