### ISSUE TITLE
Mapping of multi-use lists (IX:8-9)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/government-procurement-agreement#22]
We need to find an expert who knows how these are used in real procedures.

Article IX:8-9

**Comment by jpmckinney** [comment]
Australia uses these lists: 
https://www.austrade.gov.au/About/Corporate-Information/Tenders
https://www.defence.gov.au/MUL.asp

This is a study about them: https://www.anao.gov.au/work/performance-audit/establishment-and-use-multi-use-lists

**Comment by jpmckinney** [comment]
We should catch up with Nico (OCP) about how multi-use lists are referenced in trade agreements as a proxy for framework agreements – to ensure that we explain ‘multi-use list’ correctly in the documentation. We can also talk to Chile and Canada about their trade agreements, and what they understand by ‘multi-use list’.

**Comment by ColinMaudry** [comment]
Reading the Australian study

> Inclusion of a supplier on a MUL does not involve a value for money assessment of suppliers and does not usually create a contractual relationship.

means no contract and award criteria

> Procurement panels are established following a competitive value for money assessment process and involve a contractual relationship for a set period of time. Once established, panels generally provide ready access to goods and services, particularly for high value procurements as the additional rules in the CPRs for such procurements do not apply. Generally, panels do not allow for new suppliers to be added to the panel once established.

Aren't procurement panels like DPS?

**Comment by ColinMaudry** [comment]
Although I didn't read it, I assume a mult-use list of qualified suppliers can be used for several procurement procedures.

**Comment by jpmckinney** [comment]
> Although I didn't read it, I assume a multi-use list of qualified suppliers can be used for several procurement procedures.

Yes, that is my understanding.

@duncandewhurst Do you happen to know if "Procurement panels" in Australia are framework agreements? (The term isn't in the framework agreements book)

**Comment by duncandewhurst** [comment]
The framework agreements book mentions that "panel contracts" are framework agreements and metions that they can be open or closed. That fits with the description of "procurement panels" by the ANAO [here](https://www.anao.gov.au/work/performance-audit/establishment-and-use-procurement-panels) and the description of "panel arrangements"  by the Department of Finance [here](https://www.finance.gov.au/government/procurement/buying-australian-government/panel-arrangements).

So, in Australia, "panel contracts", "panel arrangements" and "procurement panels" seem to be synonyms - and also framework agreements.

**Comment by ColinMaudry** [comment]
Since we don't have data or real world use cases of multi-use lists, we'll ask interested people to share their data with the helpdesk so that we can write guidance.

**Comment by jpmckinney** [comment]
Closing until there is demand.
