### ISSUE TITLE
Add an id HTML attribute to each row

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/government-procurement-agreement#23]
i.e. add `id="VII:2"` etc. attributes so that we can add links to refer back to earlier mappings. 

In the EU profile, we wrote "Same as … above" and then repeated the mapping, like at the bottom of [F01](https://standard.open-contracting.org/profiles/eu/master/en/forms/F01/).

**Comment by ColinMaudry** [comment]
Partly automated with the following regex: `s/<tr>\(\n\s*\)<td>\([A-Z]*:[0-9]([a-z])\)/<tr id="\2">\1<td>\2/g`.

**Comment by ColinMaudry** [comment]
> In the EU profile, we wrote "Same as … above" and then repeated the mapping, like at the bottom of F01.

In the EU profile, this equivalence is not managed in the markdown but somewhere in the script.

I have simply add a link on all the references, trying to prevent issues with the parenthesis:

```markdown
follow the guidance for VII:2(b)
```

is now

```markdown
follow the guidance for [VII:2(b)](<#VII:2(b)>)
````

Using the following regex: `s/\(ollow the guidance for\) \([A-Z]\+:[1-9]\(([a-z])\)\?\)/\1 [\2](<#\2>)/g`

**Comment by jpmckinney** [comment]
Sounds good to me!

**Comment by jpmckinney** [comment]
I'm not sure that this is closed? (I haven't seen a PR.)
