### ISSUE TITLE
XVI:4: Distinguishing central government entities, sub-central government and other entities

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting-extensions/government-procurement-agreement#29]
Article XVI:4 is about producing statistics on past procedures.

The produced statistics must distinguish the statistics according to the type of procuring entity:

- Annex 1: central government entities
- Annex 2 (sub-central government entities) and 3 (other entities)

Question: how can one categorize buyers the GPA way using OCDS data?

Source of the meaning of Annex 1,2,3: https://www.wto.org/english/tratop_e/gproc_e/gp_app_agree_e.htm

**Comment by ColinMaudry** [comment]
Annex 1 procuring entities in the EU are listed here:
Annex 2 procuring entities in the EU are defined [here](https://e-gpa.wto.org/en/Annex/Details?Agreement=GPA113&Party=EuropeanUnion&AnnexNo=2&ContentCulture=en)
Annex 3 procuring entities in the EU are defined [here](https://e-gpa.wto.org/en/Annex/Details?Agreement=GPA113&Party=EuropeanUnion&AnnexNo=3&ContentCulture=en)

Links to the annexes for other countries and regions can be found in [the table](https://www.wto.org/english/tratop_e/gproc_e/gp_app_agree_e.htm#revisedGPA)

**Comment by ColinMaudry** [comment]
We could suggest GPA profile implementers to fill in `Party.details` with information about the procuring entity's GPA category (annex-1, annex-2, annex-3).

**Comment by jpmckinney** [comment]
Yes, that sounds good. By the way, this notebook shows how the statistics can be calculated using OCDS data: https://colab.research.google.com/drive/1eEf22g9LlpWard8t7FoIAvDMALik7aOC

We might want to link to it.
