### ISSUE TITLE
XVI-4: Guidance to produce statistics 

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting-extensions/government-procurement-agreement#45]
We currently don't know the best way to write useful guidance on how to produce statistics as described in [chapter XVI:4](https://www.wto.org/english/docs_e/legal_e/rev-gpr-94_01_e.htm#articleXVI) of the GPA.

We could:

- use natural language

> * Select records where `compiledRelease/buyer/id` refers to a `Party` object in the record's `compiledRelease/parties` array where a `Classification` object in the party's `details/classifications` has:
>   * 'gpaCoverageSchedule' as its `scheme`
>   * 'annex1' as its `id`

- use pseudo-code
- use an actual query language such as the one used in [jq](https://stedolan.github.io/jq/manual/)
- do something else

Feedback from GPA adopters is welcome.

**Comment by jpmckinney** [comment]
Closing until there is demand.
