### ISSUE TITLE
Legal basis

### ISSUE THREAD

**Issue by PaulBoroday** [open-contracting-extensions/government-procurement-agreement#5]
Maybe it is makes some sense to add url of legal framework witch is a basis for this process? Its especially be advisable in case of <National procurement law>

**Comment by jpmckinney** [comment]
The EU uses a [code list of legal references](http://publications.europa.eu/mdr/resource/eprocurement/ted/R2.0.9/publication/latest/code_lists/t_legal-basis_PublicProcurement.xsd), that are easy to look up without URLs.

Closing as not related to GPA work.
