### ISSUE TITLE
NUTS code of 'buyer'

### ISSUE THREAD

**Issue by PaulBoroday** [open-contracting-extensions/government-procurement-agreement#6]
Concern is that according to suggestion we will get two 'address' objects for 'buyer'.
One here: parties.address (as a usual 'address' object')
One here: parties/details/address

Suggestion is that as far as NUTS code is a attribute describing a geography, maybe its make sense to keep it in existing 'address' object as optional field?

**Comment by jpmckinney** [comment]
@PaulBoroday: Your issues are relevant to the upcoming EU profile. However, I don't believe any of them are specific to GPA. For example, NUTS is an EU-standard, so doesn't belong in general GPA guidance (which is for the whole world).

**Comment by jpmckinney** [comment]
^ Agreed. Moving to https://github.com/open-contracting/standard/issues/739.
