### ISSUE TITLE
Web address of the buyer profile

### ISSUE THREAD

**Issue by PaulBoroday** [open-contracting-extensions/government-procurement-agreement#7]
Absolutely agree with suggestion to move it to 'details' but maybe its better to leave naming - 'buyerProfile'. Because such definition is more understandable and univocal than 'url' (remembering than 'buyerProflie' is not just some  'url' but a list of planned procurements - basically url of package of ocid's containing APP)

**Comment by jpmckinney** [comment]
Will do. Closing here, though, as this repo is for GPA (not EU).
