### ISSUE TITLE
is a central purchasing body

### ISSUE THREAD

**Issue by PaulBoroday** [open-contracting-extensions/government-procurement-agreement#8]
I guess CBP is neither Boolean nor enum value. Maybe for mapping its ok, but for processes - its may not be enough Besides. CPB is not always 'buyer' (meaning Entity who is using the items being procured or whos budget will be spended to cover conducted contract). Even TED form says  "The contract is awarded by a central purchasing body" (true/false). Its not about 'buyer', in fact.

In different cases (especially in multi-stage processes like FA) range of responsibility of CPB may scale from just 'procuring Entity' up to  'Contacting Authority' for Framework Agreement (as document)  or even to 'buyer' in a second-stage competition. Not necessary, but can be.

From that point f view - CBP might be considered as a separate 'role' of entity involved in contracting process. This will allow to use this data not just as a flag or string value, but as a 'hook' to build relevant process steps, required in case of involving of CPB in this or that stage of contracting process

**Comment by jpmckinney** [comment]
Agreed that 'centralPurchasingBody' should be a new party role.

Just to clarify: Section I of a TED form is about contracting authorities, which maps to `buyer` in OCDS. So, the checkbox in Section I about CBP is about the buyer.

**Comment by jpmckinney** [comment]
Closing as this will be handled in EU work, not GPA work.
