### ISSUE TITLE
Communication. Availability or restriction of tender documents

### ISSUE THREAD

**Issue by PaulBoroday** [open-contracting-extensions/government-procurement-agreement#9]
Don't you think that this is about 'procurementMethod'?

**Comment by jpmckinney** [comment]
No, in [2014/24/EU](https://eur-lex.europa.eu/eli/dir/2014/24/oj), you can have "unrestricted and full direct access" in a "restricted procedure", or restricted access in an open procedure. They are different concepts.

Closing as not related to GPA work.
